# =============================================================================
# Access Route4Me's logistics-as-a-service API using our C# SDK
#
# Copyright (C) 2016-2017 Route4Me
#
# =============================================================================

sudo: required
language: csharp
solution: Route4MeSDK.sln

mono: none
#  - latest
#  - 3.8.0  The project is upgraded to .Net 4.6.1 and this point will be failed
#  - 2.10.8 # fails: https://travis-ci.org/maxkoryukov/route4me-csharp-sdk/jobs/194265821  

# dotnet:
#   - 1.0.0-preview2-003121

cache:
  directories:
    - packages

script:
#  - xbuild /p:Configuration=Release ./Route4MeSDKLibrary/Route4MeSDKLibrary.csproj
#  - xbuild /p:Configuration=Release ./Route4MeSDKUnitTest/Route4MeSDKUnitTest.csproj
  - mono ./packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Route4MeSDKUnitTest/bin/Debug/Route4MeSDKUnitTest.dll # MsTest Not supported on Travis
